name: Install Rust tool chain and protoc

inputs:
    target:
        description: "Specified target for rust toolchain, ex. x86_64-apple-darwin"
        type: string
        required: false
        defalt: "x86_64-unknown-linux-gnu"
        options:
            - x86_64-unknown-linux-gnu
            - aarch64-unknown-linux-gnu
            - x86_64-apple-darwin
            - aarch64-apple-darwin
            - aarch64-unknown-linux-musl
            - x86_64-unknown-linux-musl
    github-token:
        description: "GitHub token"
        type: string
        required: true


runs:
    using: "composite"
    steps:
        - name: Install Rust toolchain
          if: "${{ inputs.target != 'x86_64-unknown-linux-musl' && inputs.target != 'aarch64-unknown-linux-musl' }}"
          uses: dtolnay/rust-toolchain@stable
          with:
              targets: ${{ inputs.target }}

        - name: Install protoc (protobuf)
          if: "${{ inputs.target != 'x86_64-unknown-linux-musl' && inputs.target != 'aarch64-unknown-linux-musl' }}"
          uses: arduino/setup-protoc@v3
          with:
              version: "25.1"
              repo-token: ${{ inputs.github-token }}
